name: Python Tests

on: 
  push:
    branches: [ "master", "development", "release" ]
  pull_request:
    branches: [ "master", "development", "release" ]

jobs:
  test:
    runs-on: ubuntu-latest  

    steps:
      - name: Checkout code 
        uses: actions/checkout@v2  

      - name: Set up Python  
        uses: actions/setup-python@v2 
        with:
          python-version: '3.8'  

      - name: Install dependencies  
        run: |  
          python -m pip install --upgrade pip  
          pip install -r requirements.txt
          pip install sphinx sphinx-autodoc-typehints  

      - name: Run tests  
        run: |  
          python -m unittest discover  

      - name: Build the documentation
        run: |
          cd docs
          sphinx-build -b html . _build/html

      - name: Deploy documentation
        run: |
          mkdir -p docs/_build/html
          cp -r _build/html/* docs/
